config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'story', to: 'pages#story'
  get 'team', to: 'pages#team'
  get 'menu', to: 'pages#menu'
  get 'responsibility', to: 'pages#responsibility'
  # resources :reviews, only: [:index, :new, :create]
  # resources :reviews, only: [:index]
  resources :reviews
  # get 'review', to: 'reviews#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :comment, presence: true
  validates :stars, presence: true

  # def average_rating
  #   average = reviews.sum(:stars).round(2)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def story
  end

  def team
  end

  def menu
  end

  def responsibility
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    @average = (@reviews.sum(:stars) / @reviews.count).to_i
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(:id)
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:name, :email, :comment, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Smoko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="shortcut icon" type="image/x-icon" href="/assets/logo.jpg" />
    <meta name="description" content="Curators of quality coffee, healthy meals and delicious macarons, Smoko specializes in delivering customized coffee and tea and all things in between.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-section col-s-12">
      <div class="nav-bar-top col-s-12">
        <%= image_tag "logo.jpg", alt: "logo", class: "logo" %>
        <h1 class="title"> <%= link_to "smoko", root_path %> </h1>
        <div class="icons">
          <%= link_to "https://www.facebook.com/Smoko-Coffee-788828204568094/", target: "_blank" do %>
            <i class="fab fa-facebook" data-toggle="tooltip" data-placement="auto" title="Check out our Facebook!"></i>
          <% end %>
          <%= mail_to "coffeesmoko@gmail.com" do %>
            <i class="far fa-envelope" data-toggle="tooltip" data-placement="auto" title="Send us an e-mail!"></i>
          <% end %>
        </div>
      </div>
      <ul class="navbar nav-pills col-s-12">
        <li class="nav-item col-s-4 col-x-2"><%= link_to "our story", story_path %></li>
        <!-- <li class="nav-item"><%#= link_to "our story", story_path, class: "nav-link active" %></li> -->
        <li class="nav-item col-s-4 col-x-2"><%= link_to "our team", team_path %></li>
        <li class="nav-item col-s-4 col-x-2"><%= link_to "our menu", menu_path %></li>
        <li class="nav-item col-s-4 col-x-2"><%= link_to "our reviews", reviews_path %></li>
        <li class="nav-item col-s-4 col-x-2"><%= link_to "social responsibility", responsibility_path %></li>
        <li class="nav-item col-s-4 col-x-2"><%= link_to "contact us", contact_path %></li>
      </ul>
    </div>
    <%= yield %>
    <div class="footer">
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="page" id="page">
  <div class="container">
    <div class="title">
        <h1>how to find us</h1>
    </div>
    <div class="contact-info">
      <div class="contact-description">
        <h5>Address:</h5>
        <p>9 Wang On Rd, Fortress Hill, Hong Kong</p>
        <h5>Opening Hours:</h5>
        <p>Monday-Saturday - 8:30-7:00</p>
        <p>Closed on Sundays</p>
        <h5>Phone:</h5>
        <p>(852)1245-5678</p>
          <%= image_tag "coffee-cups-with-plants.jpg", alt: "smoko shop image", class: "smoko-shop" %>
      </div>


      <div class="map">
        <div class="gmap_canvas">
          <iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=smoko%20wang%20on%20road&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
          </iframe>
        </div>
        <style>.map{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}
        </style>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
<div class="page" id="page">
  <div class="cards" id="cards">
    <div class="card col-12 col-lg-6">
      <%= image_tag "hot-coffee.jpg", alt: "hot coffee image" %>
      <%= link_to story_path do %>
        <p>our story</p>
      <% end %>
    </div>

    <div class="card col-12 col-lg-6">
      <%= image_tag "team.jpg", alt: "team image" %>
      <%= link_to team_path do %>
        <p>our team</p>
      <% end %>
    </div>

    <div class="card col-12 col-lg-6">
      <%= image_tag "minion-macarons.jpg", alt: "minion macarons image" %>
      <%= link_to menu_path do %>
        <p>our menu</p>
      <% end %>
    </div>

    <div class="card col-12 col-lg-6">
      <%= image_tag "refreshments.jpg", alt: "refreshments image" %>
      <%= link_to reviews_path do %>
        <p>our reviews</p>
      <% end %>
    </div>

    <div class="card col-12 col-lg-6">
      <%= image_tag "coffee-cups-with-plants.jpg", alt: "coffee cups with plants image" %>
      <%= link_to responsibility_path do %>
        <p>social responsibility</p>
      <% end %>
    </div>

    <div class="card col-12 col-lg-6">
      <%= image_tag "cny-macarons.jpg", alt: "chinese new year macarons image" %>
      <%= link_to contact_path do %>
        <p>contact us</p>
      <% end %>
    </div>
  <!-- <div id="fakeContent"></div> -->
  </div>
  <!-- </div> -->
</div>

app/views/pages/menu.html.erb
<div class="page" id="page">
  <div class="container">
    <h1>our menu</h1>
    <p>We have delicious and healthy offerings that are prepared with fresh ingredients and are fully customizable</p>

    <iframe class="menu" src="https://4355139c-fba8-4f43-a638-afa7bb56069b.filesusr.com/ugd/73604f_d1b2d6ff8b674713b8e8ac3972a5c207.pdf">
      <p>Your browser does not support iframes.</p>
    </iframe>
  </div>
</div>

<!-- <iframe class="menu" frameborder="0" allowfullscreen="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" title="YouTube video player" src="https://www.youtube.com/embed/0pgXqKTgUMg?showinfo=0&amp;mute=1&amp;modestbranding=1&amp;loop=1&amp;autoplay=1&amp;controls=0&amp;disablekb=1&amp;playlist=0pgXqKTgUMg&amp;enablejsapi=1&amp;origin=https%3A%2F%2Fwww.codechrysalis.io&amp;widgetid=1" id="widget2"></iframe> -->

app/views/pages/responsibility.html.erb
<div class="page" id="page">
  <h1>Pages#responsibility</h1>
  <p>Find me in app/views/pages/responsibility.html.erb</p>
</div>

app/views/pages/story.html.erb
<div class="page" id="page">

  <div class="container">

      <div class="story">
        <div id="carousel-story" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel-story" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-story" data-slide-to="1"></li>
            <li data-target="#carousel-story" data-slide-to="2"></li>
            <li data-target="#carousel-story" data-slide-to="3"></li>
          </ol>

          <div class="carousel-inner fadeImage">
            <div class="carousel-item active">
              <%= image_tag 'coffee-cups.jpg', alt: "mission image" %>
              <div class="carousel-caption">
                <h1>our mission</h1>
                <p>Smoko is a catalyst for hardworking men and women to feel and embrace the taste and power of coffee.</p>
              </div>
            </div>
            <div class="carousel-item">
              <%= image_tag 'hot-coffee.jpg', alt: "essence image" %>
              <div class="carousel-caption">
                <h1>our essence</h1>
                <p>At our core, Smoko operates on imagination, individuality, inclusivity, and impact.</p>
              </div>
            </div>
            <div class="carousel-item">
              <%= image_tag 'cny-macarons.jpg', alt: "promise image" %>
              <div class="carousel-caption">
                <h1>our promise</h1>
                <p>We deliver optimistic and diverse coffee tasting experiences that are custom made to satisfy your every whim.</p>
              </div>
            </div>
            <div class="carousel-item">
              <%= image_tag 'coffee-and-cinnamon-sticks.jpg', alt: "vibe image" %>
              <div class="carousel-caption">
                <h1>our vibe</h1>
                <p>At Smoko, we innovate. We are always creating new coffees through experimentation, reinventing what's possible every day.</p>
              </div>
            </div>

          <a class="carousel-control-prev" href="#carousel-story" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel-story" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <div class="page">
  <div class="container">

    <div class="cards">
      <div class="card">
        <h2>our mission</h2>
        <p>Smoko is a catalyst for hardworking men and women to feel and embrace the taste and power of coffee.</p>
      </div>

      <div class="card">
        <h2>our essence</h2>
        <p>At our core, Smoko operates on imagination, individuality, inclusivity, and impact.</p>
      </div>

      <div class="card">
        <h2>our promise</h2>
        <p>We deliver optimistic and diverse coffee tasting experiences that are custom made to satisfy your every whim.</p>
      </div>

      <div class="card">
        <h2>our vibe</h2>
        <p>At Smoko, we innovate. We are always creating new coffees through experimentation, reinventing what's possible every day.</p>
      </div>
    </div>
  </div>
</div>


 -->

app/views/pages/team.html.erb
<div class="page" id="page">
  <div class="container">
    <div class="team-content">
      <div class="team-images fadeImage" id="abc">
        <%= image_tag "founder.jpg", class: 'person sticky' %>
      </div>
      <div class="team-description">
        <!-- <div class="title sticky">
          <h1>the team</h1>
        </div> -->
        <div class="team-member-one">
          <h1>
            Wing Yeung
          </h1>
          <p>
            Wing has been in the coffee industry for over a decade. Fueled with a passion for coffee and all the intricacies that make a great cup, she started her journey working for as a barista at Starbucks. Throughout the years, she honed her skills so that one day she would be able to fulfill her dream of owning her own coffee shop. This is how Smoko started.
          </p>
        </div>
        <div class="team-member-two">
          <h1>
            Veronica Wong
          </h1>
          <p>
            Veronica has been at Smoko for the past 3 years. She has been creating masterpieces of art to everything that Smoko has to offer. The well-known cheese macarons that Smoko offers come in the form of Winnie the Pooh, Mickey Mouse, cute animals and any other design that you can think of.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="page" id="page">
  <div class="container">
    <div class="header">
      <div class="average">
        <h4>Our average rating</h4>
        <p>
          <% @average.times do %>
            <span class="fa fa-star checked average-stars"></span>
          <% end %>
        </p>
      </div>
      <div class="title">
        <h1>what people say about us</h1>
      </div>
      <div class="new-review">
        <%= link_to "Leave us a review!", new_review_path, class: "btn btn-primary" %>
      </div>
    </div>

    <div class="reviews">
      <% @reviews.each do |review| %>
        <div class="review">
          <h5>Name: <%= "#{review.name}" %></h5>
          <p>Email: <%= "#{review.email}" %></p>
          <p>Comment: <%= "#{review.comment}" %></p>
            <% "#{review.stars}".to_i.times do %>
              <span class="fa fa-star checked"></span>
            <% end %>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

          <!-- <p>Stars: <%#= "#{review.stars}" %></p>
          <span class="fa fa-star checked"></span> -->

app/views/reviews/new.html.erb
<div class="page" id="page">
  <div class="container form">
    <%= simple_form_for(@review) do |f| %>
      <%= f.input :name, label: "Name", required: true %>
      <%= f.input :email, label: "Email", required: true %>
      <%= f.input :comment, label: "Comment", required: true %>
      <%= f.input :stars, label: "Stars", collection: %w[1 2 3 4 5], required: true, class:'genForm_dropBox' %>
      <%= f.button :submit, label: "Create Review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>